# Which files SOPS encrypts, and with which age recipients.
# creation_rules are evaluated top-down; the first matching path_regex wins.
creation_rules:
  - path_regex: \.sops\.env$
    age: age1hg59ppk0907r3tvqzn7wy0adgl4rem7hxn76zhcta0wtv8k7d4eqyh9dju,age14qws48k0r3fc8pmgma6ksclw2uphy63txuqg77m4uttcu6fgusesqvp7la
  - path_regex: \.sops\.yaml$
    age: age1hg59ppk0907r3tvqzn7wy0adgl4rem7hxn76zhcta0wtv8k7d4eqyh9dju,age14qws48k0r3fc8pmgma6ksclw2uphy63txuqg77m4uttcu6fgusesqvp7la
